In [ ]:
import numpy as np
import torch


In [ ]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)


In [ ]:
y=w*x+b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [ ]:
y.backward()

In [ ]:
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
inputs=np.array([[73,67,43],
                 [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [ ]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')


In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)

print(w)
print(b)

tensor([[-1.3666,  1.0436, -0.8151],
        [-1.8046, -1.8734,  0.4296]], requires_grad=True)
tensor([0.6398, 1.2693], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t()+b

In [ ]:
preds=model(inputs)
print(preds)

tensor([[ -64.2558, -237.5170],
        [ -84.0575, -300.3215],
        [ -25.6968, -381.8569],
        [-124.0434, -247.4674],
        [ -50.5334, -273.0292]], grad_fn=<AddBackward0>)


In [ ]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
loss=mse(preds,targets)
print(loss)

tensor(86285.5703, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[-1.3666,  1.0436, -0.8151],
        [-1.8046, -1.8734,  0.4296]], requires_grad=True)
tensor([[-12375.5508, -12598.1270,  -8055.6074],
        [-31965.4492, -34955.5312, -21347.3711]])


In [ ]:
print(b)
print(b.grad)

tensor([0.6398, 1.2693], requires_grad=True)
tensor([-145.9174, -380.0384])


In [ ]:
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
preds=model(inputs)
print(preds)

tensor([[ -64.2558, -237.5170],
        [ -84.0575, -300.3215],
        [ -25.6968, -381.8569],
        [-124.0434, -247.4674],
        [ -50.5334, -273.0292]], grad_fn=<AddBackward0>)


In [ ]:
loss=mse(preds,targets)
print(loss)

tensor(86285.5703, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()

In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)

tensor([[-1.2429,  1.1695, -0.7345],
        [-1.4850, -1.5238,  0.6430]], requires_grad=True)


In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(58276.8242, grad_fn=<DivBackward0>)


In [ ]:
for i in range(1000): #loss un az olması için deneme sayısının yüksek olması lazım
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5366, grad_fn=<DivBackward0>)


In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
preds

tensor([[ 57.2717,  70.5194],
        [ 82.1401, 100.5383],
        [118.6758, 132.9240],
        [ 21.0679,  36.9887],
        [101.9376, 119.1718]], grad_fn=<AddBackward0>)