In [25]:
import numpy as np

**The Basics**


In [26]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [27]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [28]:
# Get Dimension
a.ndim

1

In [29]:
# Get Shape
b.shape

(2, 3)

In [30]:
# Get Type
a.dtype

dtype('int32')

In [31]:
# Get Size
a.itemsize

4

In [32]:
# Get total size
a.nbytes

12

In [33]:
# Get number of elements
a.size

3

**Accessing/Changing specific elements, rows, columns, etc**

In [34]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
# Get a specific element [r, c]
a[1, 5]

13

In [36]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [38]:
  # Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [39]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Get specific element (work outside in)
b[0,1,1]

4

In [42]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: ignored

In [ ]:
b

**Initializing Different Types of Arrays**

In [ ]:
# All 0s matrix
np.zeros((2,3))

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

In [ ]:
# Any other number
np.full((2,2), 99)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

In [ ]:

# The identity matrix
np.identity(5)

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

**Mathematics**

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
# Take the sin
np.cos(a)

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

**Linear Algebra**

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

**Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=1)

In [ ]:
np.sum(stats, axis=0)

**Reorganizing Arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

**Miscellaneous**

Load Data from File

In [44]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [45]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])